### ISSUE TITLE
Task "androidAnalyzerDetektConfig" fails when detekt = true

### ISSUE THREAD

**Issue by forming** [pinchbv/android-analyzer#14]
Task `androidAnalyzerDetektConfig ` fails when `detekt = true`.

Error message: `io.gitlab.arturbosch.detekt.extensions.DetektExtension.setConfig(Lorg/gradle/api/file/ConfigurableFileCollection;)V`

**Comment by AndroideRob-zz** [comment]
Could you please share with me your `androidAnalyzer { .. }` block and the exact gradle task that you are executing? That would help. Thanks.

**Comment by forming** [comment]
Running `./gradlew androidAnalyzer`
```
androidAnalyzer {
    applicationId = 'com.test.project'
    projectName = 'Test project'
    projectVersion = '4.254.0'
    detekt = true
    unitTestCoverage = false
    packageName = 'com.test.project'
    buildVariant = 'debug'
    buildBreaker = false
    sonarqubeGitBranches = false // only works with a paid license
}
```

**Comment by AndroideRob-zz** [comment]
Thank you. I am going to try to reproduce it and get back to you.

**Comment by AndroideRob-zz** [comment]
@forming could you try again with the latest version? Detekt has been out of RC and in stable, that might have solved the issue. Appreciate it.

**Comment by forming** [comment]
Seems to be working perfectly now, thank you!
