### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by doertscho** [pinchbv/android-analyzer#17]
Hi, thanks for your work on this plugin! I tested it the other week and I'd like to use it in a project, but we're a bit reluctant due to the missing license. I can't see any hints that this might be intentional, so would you consider adding one? I'm sure it would help the wider adoption of this plugin, not just for our project.

**Comment by AndroideRob-zz** [comment]
Hi, thanks for your interest and for pointing it out! I am going to let you know once the license is included.

**Comment by AndroideRob-zz** [comment]
@doertscho the license has just been added. Please let me know if we can close the issue. Thank you.

**Comment by doertscho** [comment]
Thank you very much, Rob. Are you going to make a release that contains this license as well? I'm no legal expert, but I assume that it does not apply retroactively to previosly released versions.

**Comment by AndroideRob-zz** [comment]
@doertscho Sure, you can use release 1.3.3 - it contains a license.
Let me know if there is anything else I can be of help with.

**Comment by doertscho** [comment]
Awesome, thank you very much for the prompt replies! 👍
