### ISSUE TITLE
Multi module setup

### ISSUE THREAD

**Issue by ghost** [pinchbv/android-analyzer#19]
It would be great to see in the example a multi module setup. At the moment I can only get the analysis to work on a single module. 
The project sets up correctly but the analysis does not get passed to sonarqube.

**Comment by AndroideRob-zz** [comment]
Thank you for pointing out the issue. 
I will adjust the current example to support multiple modules.

For now, could you please share how exactly are you calling the plugin in case of a multi-module setup?

Are you following the sequential principle as described in the readme?

```
// when running the plugin in multi-module environment, make sure to analyze each module separately
./gradlew app:androidAnalyzer
./gradlew core:androidAnalyzer
./gradlew feature:androidAnalyzer
```

**Comment by ghost** [comment]
Ah, I completely missed the multi module part. I was just running `./gradlew androidAnalyzer` and assuming all would run.
Looks like it is working now. Thanks!
