### ISSUE TITLE
Detekt file path setup

### ISSUE THREAD

**Issue by rahulsainani** [pinchbv/android-analyzer#31]
In a multi module project, we have a common detekt-config file, would it be possible to set a common detekt file path instead of having a detekt-config file for each module? 

Currently the plugin only allows the file name to be changed, not the path.

**Comment by AndroideRob-zz** [comment]
Hi!

In a multi-module project, you could place your `detekt-config.yml` file in the root project directory (next to project-level `build.gradle`), and then reference it in the modules' `build.gradle` in the following way: 

```
androidAnalyzer {
    ..
    detektConfigFileName = "../detekt-config.yml"
}
```

Please let me know if this helps. Good luck!

**Comment by rahulsainani** [comment]
Hey @AndroideRob Thanks for the reply, it works, so the path can be configured. Should've tried this. Apologies for the late reply. Closing this as it's not an issue.
