### ISSUE TITLE
Branche support not working

### ISSUE THREAD

**Issue by ThomasMiddel** [pinchbv/android-analyzer#6]
I enabled branche support in my Gradle file, but can only see my `develop` branche in Sonarqube somehow. I ran the analyzer without branche support first and enabled it after. Is branche support not fully working yet?

**Comment by AndroideRob-zz** [comment]
I am looking into how Jenkins resolves git branch names and fixing this in the next release.

**Comment by ThomasMiddel** [comment]
It's fixed in the 1.3.1 release, thank you @AndroideRob !
